server:
  port: 9368
  servlet:
    context-path: /redis


spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    seconds: 43200
    sentinel:
      # 哨兵模式的主机名称
      master: mymaster
      # 哨兵的ip 可配置多个用,隔开
      nodes: 192.168.3.128:26379
      # 哨兵密码
      password: 9299
    jedis:
      pool:
        max-active: 1000
        max-wait: 10000
        max-idle: 100
        min-idle: 30
    timeout: 10000
    testOnBorrow: true
    testWhileIdle: true
