server:
  port: 9368
  servlet:
    context-path: /redis


spring:
  redis:
    database: 0
    host: 192.168.190.128
    port: 6379
    password: 9299
    seconds: 43200
    jedis:
      pool:
        max-active: 1000
        max-wait: 10000
        max-idle: 100
        min-idle: 30
    timeout: 10000
    testOnBorrow: true
    testWhileIdle: true
